name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.org'
      - '.dir-locals.el'
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
      - '**.org'
      - '.dir-locals.el'

env:
  TEST_BINARY: ./zig-out/bin/jemalloc-tests

jobs:
  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        zig-version: [0.13.0, master]
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}
      - name: Install deps(Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind
      - name: Run UT
        run: |
          zig build -Dcpu=baseline --verbose
          ${TEST_BINARY}
      - name: Valgrind Test
        if: matrix.os == 'ubuntu-latest'
        run: |
          valgrind --leak-check=full --tool=memcheck \
          --show-leak-kinds=all --error-exitcode=1 ${TEST_BINARY}
